name: goal_timer
description: Tracks time until/since a goal was set
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  time_toggle_buttons:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: time_toggle_buttons
  popover_datetime_picker:
    git:
      url: https://github.com/GitHubStuff/popover_datetime_picker.git
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.3.0
  intl: ^0.17.0
  moor: ^4.4.0
  moor_flutter: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  moor_generator: ^4.3.1
  test: ^1.17.9

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  image_path: "images/brand.png"
  android: true
  ios: true
